[platformio]
default_envs = esp32_tdisplay

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -DSERVO_TESTER_VERSION=\"v1.0.0\"

lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  bblanchon/ArduinoJson @ ^7.4.3
  WiFi
  WebServer
  SPI
  LittleFS

[env:esp32_tdisplay]
board = esp32dev
build_flags =
  ${env.build_flags}
  -DCORE_DEBUG_LEVEL=3
  -DUSER_SETUP_LOADED=1
  -include include/User_Setup_TDisplay.h
